### ISSUE TITLE
complie error: No rule to make target `-lz', needed by `ffm_ps'

### ISSUE THREAD

**Issue by justinsu** [xswang/logistic_regression_ps#2]
Hello,

When I compile this project, I got an error as follows:

No rule to make target `-lz', needed by `ffm_ps'

**Comment by xswang** [comment]
hi~
maybe you should install lz4-r129.tar.gz
<https://github.com/xswang/logistic-regression-ftrl-ps/blob/master/ps-lite/third_party/lz4-r129.tar.gz>
on
your machine.

2017-11-14 15:48 GMT+08:00 justinsu <notifications@github.com>:
